[project]
name = "build-transformer-engine-torch-gpu-tests"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "numpy>=1.24,<3",
    "pytest>=8,<10",
    "torch==2.10.0+cu128",
    "transformer-engine-torch==2.16.0+cu.12.8.torch.2.10",
    "transformer-engine[core]==2.16.0",
]

[tool.uv]
environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]

[tool.uv.sources]
transformer-engine-torch = { index = "astral-cu128" }
torch = { index = "pytorch-cu128" }

[[tool.uv.index]]
name = "astral-cu128"
url = "https://wheels.astral.sh/simple/cu128/"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
